site_name: Wo Es war, soll Ich werden.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.path
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: light green
      accent: teal
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Noto Serif